---

- name: Install dnsmasq
  apt:
    pkg: dnsmasq
    state: present

- name: Copy dnsmasq config
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/local.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart dnsmasq
