---

- name: Install icedove
  apt:
    pkg: '{{ item }}'
    state: present
  with_items:
    - icedove
    - enigmail
    - iceowl-extension
    - xul-ext-sogo-connector
  when: graphical and ansible_distribution == 'Debian'

- name: Install thunderbird
  apt:
    pkg: '{{ item }}'
    state: present
  with_items:
    - thunderbird
    - enigmail
    - xul-ext-lightning
    # there doesn't seem to be a proper sogo connector package
  when: graphical and ansible_distribution == 'Ubuntu'
