#!/usr/bin/env bash

set -e

# iptables tables and default chains
#   filter    INPUT, FORWARD, OUTPUT
#   nat       PREROUTING, OUTPUT, POSTROUTING
#   mangle    PREROUTING, OUTPUT, INPUT, FORWARD, POSTROUTING
#   raw       PREROUTING, OUTPUT
#   security  INPUT, OUTPUT, FORWARD

# ip6tables tables and default chains
#   filter    INPUT, FORWARD, OUTPUT
#   mangle    PREROUTING, OUTPUT, INPUT, FORWARD, POSTROUTING
#   raw       PREROUTING, OUTPUT
#   security  INPUT, OUTPUT, FORWARD

function block
{
  local iptables="${1}"
  local localhost="${2}"

  echo -n "Loading '${iptables}' blocking rules..."

  # Be more picky about what we forward.
  ${iptables} --table filter --policy FORWARD DROP

  # Be more picky about what we allow.
  ${iptables} --table filter --policy INPUT DROP

  # Attempt to protect against SYN flooding.
  ${iptables} --table filter --append INPUT \
    --protocol tcp --syn --match limit \
    --limit 25/s --limit-burst 50 --jump ACCEPT

  # Accept a few pings.
  ${iptables} --table filter --append INPUT \
    --protocol icmp --match limit \
    --limit 4/s --limit-burst 8 --jump ACCEPT

  # Accept existing connections.
  ${iptables} --table filter --append INPUT \
    --match state --state ESTABLISHED,RELATED --jump ACCEPT

  # Accept local connections.
  ${iptables} --table filter --append INPUT \
    --source ${localhost} --jump ACCEPT

  # Accept ssh.
  ${iptables} --table filter --append INPUT \
    --protocol tcp --match tcp --dport 22 --jump ACCEPT

  echo "DONE"
}

function load
{
  local iptables="${1}"
  local localhost="${2}"

  block ${iptables} ${localhost}
}

function flush
{
  local iptables="${1}"

  echo -n "Flushing '${iptables}' rules..."

  ${iptables} --table filter --policy FORWARD DROP

  ${iptables} --table filter --flush INPUT
  ${iptables} --table filter --policy INPUT DROP

  echo "DONE"
}

case "${1}" in
  start|restart)
    flush iptables
    load iptables 127.0.0.1
    flush ip6tables
    load ip6tables ::1
    ;;

  stop)
    flush iptables
    flush ip6tables
    ;;

  *)
    echo "Usage:  start|stop|restart."
    ;;
esac

exit 0
