#!/usr/bin/env bash

set -e

# iptables tables and default chains
#   filter  INPUT, FORWARD, OUTPUT
#   nat     PREROUTING, OUTPUT, POSTROUTING
#   mangle  PREROUTING, INPUT, FORWARD, OUTPUT, POSTROUTING
#   raw     PREROUTING, OUTPUT

# ip6tables tables and default chains
#   filter  INPUT, FORWARD, OUTPUT
#   mangle  PREROUTING, INPUT, FORWARD, OUTPUT, POSTROUTING
#   raw     PREROUTING, OUTPUT

function load
{
  echo -n "Loading IPv4 rules..."
  iptables -P FORWARD DROP

  iptables -P INPUT DROP
  iptables -A INPUT -p tcp --syn -m limit --limit 25/s --limit-burst 50 \
    -j ACCEPT
  iptables -A INPUT -p icmp -m limit --limit 4/s --limit-burst 8 -j ACCEPT
  iptables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT  # ssh
  iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
  iptables -A INPUT -s 127.0.0.1 -j ACCEPT
  echo "DONE"

  echo -n "Loading IPv6 rules..."
  ip6tables -P FORWARD DROP

  ip6tables -P INPUT DROP
  ip6tables -A INPUT -p tcp --syn -m limit --limit 25/s --limit-burst 50 \
    -j ACCEPT
  ip6tables -A INPUT -p icmp -m limit --limit 4/s --limit-burst 8 -j ACCEPT
  ip6tables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT  # ssh
  ip6tables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
  ip6tables -A INPUT -s ::1 -j ACCEPT
  echo "DONE"
}

function flush
{
  echo -n "Flushing IPv4 rules..."
  iptables -P FORWARD ACCEPT

  iptables -F INPUT
  iptables -P INPUT ACCEPT
  echo "DONE"

  echo -n "Flushing IPv6 rules..."
  ip6tables -P FORWARD ACCEPT

  ip6tables -F INPUT
  ip6tables -P INPUT ACCEPT
  echo "DONE"
}

case "${1}" in
  start|restart)
    flush
    load
    ;;
  stop)
    flush
    ;;
  *)
    echo "Usage:  start|stop|restart."
    ;;
esac

exit 0
