---

- name: Install pip
  easy_install:
    name: pip
    state: present

- name: Install virtualenv
  pip:
    name: virtualenv
    state: present

- name: Install brew
  command: ruby -e '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)'

- name: Install brew packages
  homebrew:
    name: '{{ item }}'
    state: present
  loop:
    - git
    - macvim
    - gpg
    - rename
    - wget

- name: Upgrade brew packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
